include:
  - project: "tulibraries/gitlab-ci-templates"
    file:
      - "lint_docker.yaml"
      - "build_docker.yaml"
      - "security_scan.yaml"
      - "kubectl_commands.yaml"
    ref: "4a283714e245f86b332311e5c8fed7d28da85be6"

variables:
  IMAGE: "tulibraries/tupress"

.export_variables: &export_variables
  - source .env
  - export VERSION="${DOCKER_IMAGE_VERSION}-${CI_COMMIT_SHORT_SHA}"

before_script:
  - *export_variables

stages:
  - build
  - scan


build:
  stage: build
  extends: .build_image
  variables:
    DF: ".docker/app/Dockerfile --build-arg RAILS_MASTER_KEY=$MASTER_KEY --no-cache"

scan:
  stage: scan
  extends: .scanimage_high
