version: "3.4"

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres

  test_app:
    build:
      context: .
      dockerfile: .docker/app/Dockerfile
      target: builder
      args:
        BASE_IMAGE: $local_base_image
        RAILS_ENV: "test"
    image: press_6-test_app:builder

    ports:
      - "3000"
    environment:
      RAILS_ENV: "test"
      TUPRESS_DB_HOST: db
      TUPRESS_DB_NAME: tupress-test
      TUPRESS_DB_PASSWORD: postgres
      TUPRESS_DB_USER: postgres
    
    depends_on:
      db:
        condition: service_started

    entrypoint:
      - "tail"
      - "-f"
      - /dev/null
