version: "3.4"

services:
  db:
    image: mysql:5.7.41
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: press_6_db
      MYSQL_ROOT_PASSWORD: press_6_ci

  test_app:
    build:
      context: .
      dockerfile: .docker/app/Dockerfile
      args:
        BASE_IMAGE: $BASE_IMAGE
        RAILS_ENV: "test"

    ports:
      - "3000"
    environment:
      RAILS_ENV: "test"
      TUPRESS_DB_HOST: db
      TUPRESS_DB_NAME: press_6_db
      TUPRESS_DB_PASSWORD: press_6_ci

    entrypoint:
      - "tail"
      - "-f"
      - /dev/null
