version: "3.4"

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_PASSWORD: press_6_ci
      POSTGRES_USER: press_6_user

  test_app:
    build:
      context: .
      dockerfile: .docker/app/Dockerfile
      args:
        BASE_IMAGE: $LOCAL_BASE_IMAGE
        RAILS_ENV: "test"

    ports:
      - "3000"
    environment:
      RAILS_ENV: "test"
      TUPRESS_DB_HOST: db
      TUPRESS_DB_NAME: press_6_db
      TUPRESS_DB_PASSWORD: press_6_ci
    
    depends_on:
      db:
        condition: service_started

    entrypoint:
      - "tail"
      - "-f"
      - /dev/null
