version: 2.1

workflows:
  test_and_scan:
    jobs:
      - run_tests
      - trivy_scan

orbs:
  coveralls: coveralls/coveralls@2.2.4

jobs:
  run_tests:
    docker:
      - image: cimg/ruby:3.3.5-node
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout

      - restore_cache:
          keys:
            - gem-cache-v6-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - gem-cache-v6-{{ arch }}-{{ .Branch }}
            - gem-cache-v6-{{ arch }}
            - yarn-cache-v6-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}

      - setup_remote_docker:
          docker_layer_caching: false

      - run: if [ -e /var/run/docker.sock ]; then sudo chown circleci:circleci /var/run/docker.sock; fi

      - run:
          name: remove dockerignore
          command: rm .dockerignore

      - run:
          name: Build docker containers
          command: |
            source .env && docker-compose -p press_6 -f docker-compose.yaml up -d
            sleep 30

      - run:
          name: Run linter
          command: |
              docker-compose -p press_6 -f docker-compose.yaml exec --user root test_app bundle exec  rubocop -c .rubocop.yml

      - run:
          name: Database migrations
          command: |
              docker-compose -p press_6 -f docker-compose.yaml exec --user root test_app bundle exec rails db:setup
              docker-compose -p press_6 -f docker-compose.yaml exec --user root test_app bundle exec rails db:migrate

      - run:
          name: Run ruby tests
          command: |
              docker-compose -p press_6 -f docker-compose.yaml exec --user root test_app bundle exec  rake spec
              docker cp press_6-test_app-1:/app/coverage/lcov/app.lcov ./app.lcov

      - coveralls/upload:
          coverage_file: ./app.lcov

  trivy_scan:
    docker:
      - image: aquasec/trivy:latest
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD

    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: false

      - run: if [ -e /var/run/docker.sock ]; then chown circleci:circleci /var/run/docker.sock; fi

      # Restore cache if available
      - restore_cache:
          keys:
            - trivy-db-{{ .Environment.CIRCLE_JOB }}-{{ epoch_week }}

      - run:
          name: Build local docker image
          command: "source .env && \
            docker build \
            --build-arg BASE_IMAGE=${LOCAL_BASE_IMAGE} \
            --build-arg RAILS_ENV=test \
            -t trivy-ci-test:${CIRCLE_SHA1} -f .docker/app/Dockerfile ."

      # Download the Java DB for Trivy
      - run:
          name: Download Trivy Java DB
          command: |
            mkdir -p /root/.cache/trivy
            trivy --cache-dir /root/.cache/trivy java-db update
      
      # Run Trivy with database cache directory set
      - run:
          name: Run Trivy scan with Java DB
          command: |
            mkdir -p /root/.cache/trivy
            GITHUB_TOKEN=$TRIVY_AUTH_TOKEN trivy --cache-dir /root/.cache/trivy image --exit-code 0 --severity CRITICAL --no-progress --scanners vuln trivy-ci-test:${CIRCLE_SHA1}

      # Save the Trivy cache to CircleCI
      - save_cache:
          key: trivy-db-{{ .Environment.CIRCLE_JOB }}-{{ epoch_week }}
          paths:
            - /root/.cache/trivy

      


    
