 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/agencies", type: :request do
  # Agency. As you add validations to Agency, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Agency.create! valid_attributes
      get agencies_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      agency = Agency.create! valid_attributes
      get agency_url(agency)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_agency_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      agency = Agency.create! valid_attributes
      get edit_agency_url(agency)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Agency" do
        expect {
          post agencies_url, params: { agency: valid_attributes }
        }.to change(Agency, :count).by(1)
      end

      it "redirects to the created agency" do
        post agencies_url, params: { agency: valid_attributes }
        expect(response).to redirect_to(agency_url(Agency.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Agency" do
        expect {
          post agencies_url, params: { agency: invalid_attributes }
        }.to change(Agency, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post agencies_url, params: { agency: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested agency" do
        agency = Agency.create! valid_attributes
        patch agency_url(agency), params: { agency: new_attributes }
        agency.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the agency" do
        agency = Agency.create! valid_attributes
        patch agency_url(agency), params: { agency: new_attributes }
        agency.reload
        expect(response).to redirect_to(agency_url(agency))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        agency = Agency.create! valid_attributes
        patch agency_url(agency), params: { agency: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested agency" do
      agency = Agency.create! valid_attributes
      expect {
        delete agency_url(agency)
      }.to change(Agency, :count).by(-1)
    end

    it "redirects to the agencies list" do
      agency = Agency.create! valid_attributes
      delete agency_url(agency)
      expect(response).to redirect_to(agencies_url)
    end
  end
end
