 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/conferences", type: :request do
  # Conference. As you add validations to Conference, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Conference.create! valid_attributes
      get conferences_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      conference = Conference.create! valid_attributes
      get conference_url(conference)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_conference_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      conference = Conference.create! valid_attributes
      get edit_conference_url(conference)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Conference" do
        expect {
          post conferences_url, params: { conference: valid_attributes }
        }.to change(Conference, :count).by(1)
      end

      it "redirects to the created conference" do
        post conferences_url, params: { conference: valid_attributes }
        expect(response).to redirect_to(conference_url(Conference.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Conference" do
        expect {
          post conferences_url, params: { conference: invalid_attributes }
        }.to change(Conference, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post conferences_url, params: { conference: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested conference" do
        conference = Conference.create! valid_attributes
        patch conference_url(conference), params: { conference: new_attributes }
        conference.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the conference" do
        conference = Conference.create! valid_attributes
        patch conference_url(conference), params: { conference: new_attributes }
        conference.reload
        expect(response).to redirect_to(conference_url(conference))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        conference = Conference.create! valid_attributes
        patch conference_url(conference), params: { conference: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested conference" do
      conference = Conference.create! valid_attributes
      expect {
        delete conference_url(conference)
      }.to change(Conference, :count).by(-1)
    end

    it "redirects to the conferences list" do
      conference = Conference.create! valid_attributes
      delete conference_url(conference)
      expect(response).to redirect_to(conferences_url)
    end
  end
end
