 # frozen_string_literal: true

 require "rails_helper"

 # This spec was generated by rspec-rails when you ran the scaffold generator.
 # It demonstrates how one might use RSpec to test the controller code that
 # was generated by Rails when you ran the scaffold generator.
 #
 # It assumes that the implementation code is generated by the rails scaffold
 # generator. If you are using any extension libraries to generate different
 # controller code, this generated spec may or may not pass.
 #
 # It only uses APIs available in rails and/or rspec-rails. There are a number
 # of tools you can use to make these specs even more expressive, but we're
 # sticking to rails and rspec-rails APIs to keep things simple and stable.

 RSpec.describe "/webpages", type: :request do
   # Webpage. As you add validations to Webpage, be sure to
   # adjust the attributes here as well.
   let(:valid_attributes) {
     skip("Add a hash of attributes valid for your model")
   }

   let(:invalid_attributes) {
     skip("Add a hash of attributes invalid for your model")
   }

   describe "GET /index" do
     it "renders a successful response" do
       Webpage.create! valid_attributes
       get webpages_url
       expect(response).to be_successful
     end
   end

   describe "GET /show" do
     it "renders a successful response" do
       webpage = Webpage.create! valid_attributes
       get webpage_url(webpage)
       expect(response).to be_successful
     end
   end

   describe "GET /new" do
     it "renders a successful response" do
       get new_webpage_url
       expect(response).to be_successful
     end
   end

   describe "GET /edit" do
     it "render a successful response" do
       webpage = Webpage.create! valid_attributes
       get edit_webpage_url(webpage)
       expect(response).to be_successful
     end
   end

   describe "POST /create" do
     context "with valid parameters" do
       it "creates a new Webpage" do
         expect {
           post webpages_url, params: { webpage: valid_attributes }
         }.to change(Webpage, :count).by(1)
       end

       it "redirects to the created webpage" do
         post webpages_url, params: { webpage: valid_attributes }
         expect(response).to redirect_to(webpage_url(Webpage.last))
       end
     end

     context "with invalid parameters" do
       it "does not create a new Webpage" do
         expect {
           post webpages_url, params: { webpage: invalid_attributes }
         }.to change(Webpage, :count).by(0)
       end

       it "renders a successful response (i.e. to display the 'new' template)" do
         post webpages_url, params: { webpage: invalid_attributes }
         expect(response).to be_successful
       end
     end
   end

   describe "PATCH /update" do
     context "with valid parameters" do
       let(:new_attributes) {
         skip("Add a hash of attributes valid for your model")
       }

       it "updates the requested webpage" do
         webpage = Webpage.create! valid_attributes
         patch webpage_url(webpage), params: { webpage: new_attributes }
         webpage.reload
         skip("Add assertions for updated state")
       end

       it "redirects to the webpage" do
         webpage = Webpage.create! valid_attributes
         patch webpage_url(webpage), params: { webpage: new_attributes }
         webpage.reload
         expect(response).to redirect_to(webpage_url(webpage))
       end
     end

     context "with invalid parameters" do
       it "renders a successful response (i.e. to display the 'edit' template)" do
         webpage = Webpage.create! valid_attributes
         patch webpage_url(webpage), params: { webpage: invalid_attributes }
         expect(response).to be_successful
       end
     end
   end

   describe "DELETE /destroy" do
     it "destroys the requested webpage" do
       webpage = Webpage.create! valid_attributes
       expect {
         delete webpage_url(webpage)
       }.to change(Webpage, :count).by(-1)
     end

     it "redirects to the webpages list" do
       webpage = Webpage.create! valid_attributes
       delete webpage_url(webpage)
       expect(response).to redirect_to(webpages_url)
     end
   end
 end
