name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ main ]
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run docker compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "${{ github.workspace }}/docker-compose.yml"

      - name: Bring up services with docker-compose
        run: |
          docker compose -p press_6 -f docker-compose.yaml up -d
          sleep 30

      - name: Run RuboCop linter
        run: |
          docker compose -p press_6 -f docker-compose.yaml \
            exec --user root test_app \
            bundle exec rubocop -c .rubocop.yml

      - name: Run DB setup + migrations
        run: |
          docker compose -p press_6 -f docker-compose.yaml \
            exec --user root test_app bundle exec rails db:setup
          docker compose -p press_6 -f docker-compose.yaml \
            exec --user root test_app bundle exec rails db:migrate

      - name: Run RSpec suite
        run: |
          docker compose -p press_6 -f docker-compose.yaml \
            exec --user root test_app bundle exec rake spec
          docker cp press_6-test_app-1:/app/coverage/lcov/app.lcov ./app.lcov

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./app.lcov