name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ main ]
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx (for docker-compose)
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose plugin
        run: |
          mkdir -p ~/.docker/cli-plugins
          curl -SL https://github.com/docker/compose/releases/download/v2.23.1/docker-compose-linux-x86_64 \
            -o ~/.docker/cli-plugins/docker-compose
          chmod +x ~/.docker/cli-plugins/docker-compose

      - name: Remove .dockerignore
        run: rm .dockerignore

      - name: Build & start containers
        run: |
          source .env
          # extract, lowercase & sanitize the base image string:
          TAG=$(grep 'ARG BASE_IMAGE' .docker/app/Dockerfile \
            | sed 's/.*="\(.*\)".*/\1/' \
            | sed 's#harbor\.k8s\.temple\.edu/library/##' \
            | tr '[:upper:]' '[:lower:]' \
            | tr ':' '-')
          echo "Using tag → $TAG"
          # use docker compose here if you prefer, but make sure to use the sanitized $TAG
          docker build \
            --build-arg BASE_IMAGE="$BASE_IMAGE" \
            -t yourapp:"$TAG" \
            -f .docker/app/Dockerfile \
            .
          docker run -d --name test_app yourapp:"$TAG"
          sleep 30

      - name: Run RuboCop linter
        run: |
          docker compose -p press_6 -f docker-compose.yaml \
            exec --user root test_app \
            bundle exec rubocop -c .rubocop.yml

      - name: Run DB setup + migrations
        run: |
          docker compose -p press_6 -f docker-compose.yaml \
            exec --user root test_app bundle exec rails db:setup
          docker compose -p press_6 -f docker-compose.yaml \
            exec --user root test_app bundle exec rails db:migrate

      - name: Run RSpec suite
        run: |
          docker compose -p press_6 -f docker-compose.yaml \
            exec --user root test_app bundle exec rake spec
          docker cp press_6-test_app-1:/app/coverage/lcov/app.lcov ./app.lcov

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./app.lcov